### PR TITLE
Feat/readme improvements

### PR DESCRIPTION
**Pull request by TeaBizzy**
* Fix: Reduced amount of html in the readme.
+ Add: File locations as comments to the How to Contribute section.

### CODE REVIEW

**Comment by NonpareilNic** [comment]
# Comments

## ChatGPT's Repsonse:

Best practice for creating a readme file is to use markdown format, as it is commonly used in many development environments and is easy to read and write. Markdown is also preferred because it is supported by most platforms and tools that display readme files.

In markdown, you can use the hash symbol (#) to create headers. The number of hash symbols denotes the header level. For example:

# This is a level 1 header
## This is a level 2 header
### This is a level 3 header
On the other hand, using HTML tags such as <h2> for headers is not recommended, as it can complicate the readme file and may not render properly in some environments. Additionally, using markdown instead of HTML makes the file more portable, allowing it to be easily converted to other formats like HTML if needed.

Here's an example of a readme file using markdown headers:

# Project Title
## Description
This is a brief description of the project.

## Installation
Here are the steps to install the project.

## Usage
Here's how to use the project.

## Contributing
Guidelines for contributing to the project.

## License
Information about the project's license.
By following these best practices, you'll create a readable and easily maintainable readme file for your project.

**Comment by NonpareilNic** [comment]
https://readme.so is a good tool, I think NauseousWave brought to my attention

**Comment by TeaBizzy** [comment]
I will have to look into it. I thought doing things like centering and using links is impossible with markdown, if you prefer having mark down only I can make another edit. LMK

**Comment by TeaBizzy** [comment]
I have replace all HTML with markdown, as suggested.

**Review by NonpareilNic — APPROVED** [review]
image_2024-01-21_184405205-removebg-preview

**Pull request merged**
